name: 'Commit Analyzer Action'
description: 'Analyzes commits, generates verbose messages via Gemini, and updates papertrail.md'
inputs:
  gemini-api-key:
    description: 'API key for Google Gemini'
    required: true
  repo-token:
    description: 'GitHub token for repo access'
    required: true
    default: ${{ github.token }}
  papertrail-path:
    description: 'Path to papertrail.md'
    required: false
    default: 'papertrail.md'
outputs:
  summary:
    description: 'Generated commit summary'
runs:
  using: 'node20'
  main: 'index.js'