name: 'Commit Message Enhancer'
description: 'Appends a fixed string to the latest commit message'
runs:
  using: 'composite'  # No Node, just bash steps
  steps:
    - run: |
        # Get the latest commit message
        ORIGINAL_MESSAGE=$(git log -1 --pretty=%B)
        echo "Original message: $ORIGINAL_MESSAGE"

        # Append fixed string
        NEW_MESSAGE="$ORIGINAL_MESSAGE [Enhanced]"
        echo "New message: $NEW_MESSAGE"

        # Amend the commit with the new message
        git commit --amend -m "$NEW_MESSAGE"
        echo "Commit amended successfully"

        # Push the amended commit (force to overwrite)
        git push origin HEAD --force
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}  # For push auth