name: "Gemini Commit Message Generator"
description: "Generate commit messages with Google Gemini"
author: "Your Name"
inputs:
  gemini-api-key:
    description: "Google Generative AI API key"
    required: true
runs:
  using: node20
  main: dist/index.js

