name: "Gemini Commit Message Generator"
description: "Generate commit messages with Google Gemini"
author: "Your Name"
inputs:
  gemini-api-key:
    description: "Google Generative AI API key"
    required: true
runs:
  using: "node16"
  main: "index.js"
