name: Test Commit Message Enhancer
on:
  push:
    branches: [main, '**']  # Test on all branches/merges for tolerance

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For git amend/push
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only HEAD needed
          token: ${{ github.token }}  # Auth for push

      - name: Configure Git Identity  # NEW: Fixes "Author identity unknown"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@github-actions[bot].com"
          echo "Git identity set: $(git config user.name) <$(git config user.email)>"

      - name: Create Dummy File for Testing
        run: |
          echo "Test content for message enhancement" > test-dummy.txt

      - name: Initial Commit
        run: |
          git add test-dummy.txt
          git commit -m "Dummy commit to test enhancer"
          git push origin HEAD

      - name: Run Enhancer Action
        uses: ./
        # Self-reference: Tests the composite action locally

      - name: Verify Amended Message
        run: |
          AMENDED_MESSAGE=$(git log -1 --pretty=%B)
          echo "Amended message: $AMENDED_MESSAGE"
          if [[ ! "$AMENDED_MESSAGE" == *" [Enhanced]" ]]; then
            echo "❌ Test failed: No [Enhanced] appended"
            exit 1
          fi
          echo "✅ Test passed: Message enhanced successfully"